// Date: 2/11/2014 5:17:55 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package democretes.renderer.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelEssentiaDynamo extends ModelBase
{
  //fields
    ModelRenderer Top1;
    ModelRenderer Top2;
    ModelRenderer Top3;
    ModelRenderer Top4;
    ModelRenderer Base;
    ModelRenderer Side1;
    ModelRenderer Side2;
    ModelRenderer Side3;
    ModelRenderer Side4;
  
  public ModelEssentiaDynamo()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Top1 = new ModelRenderer(this, 48, 12);
      Top1.addBox(-2F, -4F, -2F, 4, 8, 4);
      Top1.setRotationPoint(2F, 12F, 2F);
      Top1.setTextureSize(64, 32);
      Top1.mirror = true;
      setRotation(Top1, 0F, 3.141593F, 0F);
      Top2 = new ModelRenderer(this, 48, 12);
      Top2.addBox(-2F, -4F, -2F, 4, 8, 4);
      Top2.setRotationPoint(2F, 12F, -2F);
      Top2.setTextureSize(64, 32);
      Top2.mirror = true;
      setRotation(Top2, 0F, -1.570796F, 0F);
      Top3 = new ModelRenderer(this, 48, 12);
      Top3.addBox(-2F, -4F, -2F, 4, 8, 4);
      Top3.setRotationPoint(-2F, 12F, 2F);
      Top3.setTextureSize(64, 32);
      Top3.mirror = true;
      setRotation(Top3, 0F, 1.570796F, 0F);
      Top4 = new ModelRenderer(this, 48, 12);
      Top4.addBox(-2F, -4F, -2F, 4, 8, 4);
      Top4.setRotationPoint(-2F, 12F, -2F);
      Top4.setTextureSize(64, 32);
      Top4.mirror = true;
      setRotation(Top4, 0F, 0F, 0F);
      Base = new ModelRenderer(this, 0, 8);
      Base.addBox(-8F, -4F, -8F, 16, 8, 16);
      Base.setRotationPoint(0F, 20F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Side1 = new ModelRenderer(this, 48, 0);
      Side1.addBox(-2F, -4F, -2F, 4, 8, 3);
      Side1.setRotationPoint(0F, 13F, 5F);
      Side1.setTextureSize(64, 32);
      Side1.mirror = true;
      setRotation(Side1, 0.5235988F, 0F, 0F);
      Side2 = new ModelRenderer(this, 48, 0);
      Side2.addBox(-2F, -4F, -2F, 4, 8, 3);
      Side2.setRotationPoint(5F, 13F, 0F);
      Side2.setTextureSize(64, 32);
      Side2.mirror = true;
      setRotation(Side2, 0.5235988F, 1.570796F, 0F);
      Side3 = new ModelRenderer(this, 48, 0);
      Side3.addBox(-2F, -4F, -2F, 4, 8, 3);
      Side3.setRotationPoint(-5F, 13F, 0F);
      Side3.setTextureSize(64, 32);
      Side3.mirror = true;
      setRotation(Side3, 0.5235988F, -1.570796F, 0F);
      Side4 = new ModelRenderer(this, 48, 0);
      Side4.addBox(-2F, -4F, -2F, 4, 8, 3);
      Side4.setRotationPoint(0F, 13F, -5F);
      Side4.setTextureSize(64, 32);
      Side4.mirror = true;
      setRotation(Side4, 0.5235988F, 3.141593F, 0F);
  }
  
  public void render() {
    final float f5 = 1F/16F;
    Top1.render(f5);
    Top2.render(f5);
    Top3.render(f5);
    Top4.render(f5);
    Base.render(f5);
    Side1.render(f5);
    Side2.render(f5);
    Side3.render(f5);
    Side4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
